# Generated by Django 2.1.7 on 2019-02-21 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'managed': False},
        ),
    ]
