# Generated by Django 2.1.7 on 2019-02-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190221_0137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='example',
            table='example',
        ),
    ]
